PDL recipe
ibm-granite-community/granite-snack-cookbook pull request #15
Opened 2024-10-11 20:29 UTC by vazirim

2024-10-14 22:09 UTC, deanwampler requested changes
I like the notebook a lot, but the last example worked very poorly. See the long comment.

I have a number of wording suggestions that I'll make with PR to your branch. They include explaining why this notebook uses an extension and I "rephrased" the mention of LiveLLM, which we don't use anywhere else. 

I also cleared the output, which is our practice. In doing so, I noticed a strange behavior for the output of the chat. Invoking "Clear outputs of all cells" in Jupyter Lab, it only erased one line of the chat interaction. I had to repeat the command multiple times to clear the _whole_ output. This seems like a bug. I'll file an issue with your repo for this one.

2024-10-14 22:09 UTC, deanwampler commented on recipes/PDL/pdl.ipynb
> +{
Change the file name to `Prompt_Description_Language.ipynb` to be more consistent with other notebooks  (although to be fair, there is a lot of inconsistency currently...)

2024-10-14 22:09 UTC, deanwampler commented on recipes/PDL/pdl.ipynb
> +    "The Prompt Declaration Language (PDL) is a YAML-based declarative approach to prompt programming, where prompts are at the forefront. PDL facilitates model chaining and tool use, abstracting awa
`LiteLLM` looks good, but it's not what we are using. I'll suggest fixes below, if it's possible to fix this...

2024-10-15 14:12 UTC, deanwampler commented on recipes/PDL/pdl.ipynb
> +    "The Prompt Declaration Language (PDL) is a YAML-based declarative approach to prompt programming, where prompts are at the forefront. PDL facilitates model chaining and tool use, abstracting awa
I forgot to delete this comment, after discussions with Adam... Sorry.

2024-10-15 14:38 UTC, rawkintrevo requested changes
Need to add this to the testing suite.

.github/workflows/vanilla_workflow.yaml
.github/notebook_lists/vanilla_notebooks.txt

2024-10-15 16:42 UTC, rawkintrevo commented
To clarify my last comment, you need to add the notebook to both files- the yaml says "fire this test if any of these files are changed", then later in the testing it loads the txt file and tests every file listed in there. 

@deanwampler specifying the files is problematic, because sometimes (in the case of ollama or the java ones) you add the path to a different yaml / text file. But changing the PR template is trivial, i can certainly add more information.

2024-10-15 16:49 UTC, deanwampler commented
Thanks. This is pure Python, so I'll add the notebook to both files in my PR to @vazirim's PR branch.

2024-10-15 19:17 UTC, vazirim commented
Hi @deanwampler, thanks for all your suggestions. I incorporated your branch in this one.

2024-10-15 20:32 UTC, deanwampler commented
I have a theory for while the CI is failing. It's not this PR's notebook. I'm going to merge this PR shortly and do a separate PR for the final steps required.

2024-10-15 22:08 UTC, merged