Speed up Summarize tests in CI
ibm-granite-community/granite-snack-cookbook pull request #31
Opened 2024-10-21 17:34 UTC by fayvor

[#149](https://github.com/ibm-granite-community/pm/issues/149)
- Truncate text in CI by looking at GRANITE_TEST env var

### PR Checklist

- [ ] **Commits signed**: All commits must be GPG or SSH signed.
- [ ] **DCO Compliance**: Developer Certificate of Origin (DCO) applies to the code, documentation, and any example data provided. Ensure commits are signed off.
- [ ] **Notebook outputs cleared**: Ensure all notebook outputs are cleared.
- [ ] **Automated testing**: Add the recipe to the automated tests.
- [ ] **Test in Google Colab**:
    - [ ] Test that it works in Google Colab (Python 3.10.12).
    - [ ] Colab has its own package set and Python version, so ensure compatibility.
- [ ] **Test locally**:
    - [ ] Ensure the code works in a fresh Python virtual environment (venv).
- [ ] **Flexible LLM platform support**:
    - [ ] The platform should be easily switchable. Use LangChain for now.
    - [ ] Include `!pip install git+https://github.com/ibm-granite-community/granite-kitchen` in the instructions.
- [ ] **Example data**: Follow the example data guidance.
- [ ] **README.md updates**:
    - [ ] Add a link to the recipe in the Table of Contents (ToC).
    - [ ] Include a Colab button after that link.

2024-10-21 17:37 UTC, fayvor commented
Tests will fail until this is merged:
https://github.com/ibm-granite-community/utils/pull/19

2024-10-21 19:42 UTC, rawkintrevo requested changes

2024-10-21 19:42 UTC, rawkintrevo commented on recipes/Summarize/Summarize.ipynb
> +    "text = book_contents if not get_env_var('GRANITE_TEST', 'false') == 'true' else book_contents[:20000]\n",
`if get_env_var('GRANITE_TEST').lower() == 'true' book_contents[:20000]

2024-10-21 20:39 UTC, adampingel commented on recipes/Summarize/Summarize.ipynb
> +    "text = book_contents if not get_env_var('GRANITE_TEST', 'false') == 'true' else book_contents[:20000]\n",
The name of the variable is `GRANITE_TESTING`

2024-10-21 22:00 UTC, fayvor commented on recipes/Summarize/Summarize.ipynb
> +    "text = book_contents if not get_env_var('GRANITE_TEST', 'false') == 'true' else book_contents[:20000]\n",
Will update.

2024-10-21 23:52 UTC, fayvor commented on recipes/Summarize/Summarize.ipynb
> +    "text = book_contents if not get_env_var('GRANITE_TEST', 'false') == 'true' else book_contents[:20000]\n",
Agentic_RAG is failing trying to load langchain_ibm for WatsonxLLM.

2024-10-22 00:45 UTC, adampingel commented on recipes/Summarize/Summarize.ipynb
> +    "text = book_contents if not get_env_var('GRANITE_TEST', 'false') == 'true' else book_contents[:20000]\n",
Will address @rawkintrevo's feedback in this ticket https://github.com/ibm-granite-community/utils/issues/20

2024-10-22 00:45 UTC, merged