Typo in Granite_Guardian_Usage_Governance_Workflow
ibm-granite-community/granite-snack-cookbook pull request #49
Opened 2024-10-24 13:51 UTC by martinscooper

2024-10-24 16:18 UTC, fayvor requested changes

2024-10-24 16:18 UTC, fayvor commented on recipes/Granite_Guardian/Granite_Guardian_Usage_Governance_Workflow.ipynb
> +    "IBM's [AI Risk Atlas](https://www.ibm.com/docs/en/watsonx/saas?topic=ai-risk-atlas) details and categories some of the risks of working with generative AI, foundation models, and machine learnin
```suggestion
    "IBM's [AI Risk Atlas](https://www.ibm.com/docs/en/watsonx/saas?topic=ai-risk-atlas) details and categorizes some of the risks of working with generative AI, foundation models, and machine learning models.\n",
```

2024-10-25 04:35 UTC, adampingel approved these changes

2024-10-26 01:18 UTC, adampingel commented
Looks like the change requested by @fayvor was implemented.  Thanks!

2024-10-26 01:18 UTC, merged