Travel planner agent recipe with granite 3.0 and LangChain Agents
ibm-granite-community/granite-snack-cookbook pull request #81
Opened 2024-11-07 14:43 UTC by manojjahgirdar

## PR Checklist

### Model Interaction

- [ ] **Flexible LLM platform support** The platform should be easily switchable. Use LangChain or LlamaIndex.
- [ ] **Use prompt guide corresponding to the model**  For example for [Granite 3.x Language Models](https://www.ibm.com/granite/docs/models/granite/#prompt-anatomy)

### Data

- [ ] **Example data**: Follow the example data guidance.

### Notebook requirements

- [ ] **Notebook outputs cleared**: Ensure all notebook outputs are cleared.
- [ ] **Automated testing**: Add the recipe to the automated tests as described [here](https://github.com/ibm-granite-community/community/wiki/Automated-Validation)
- [ ] **Test in Google Colab**:
    - [ ] Test that it works in Google Colab (Python 3.10.12).
    - [ ] Colab has its own package set and Python version, so ensure compatibility.
- [ ] **Test locally**:
    - [ ] Ensure the code works in a fresh Python virtual environment (venv).
- [ ] **Standard access to secrets and variables** Include `!pip install git+https://github.com/ibm-granite-community/utils` in the first code cell in order to make `get_env_var` available to accessing secrets and variables in the recipe.

### Incoming References

- [ ] **README.md updates**:
    - [ ] Add a link to the recipe in the Table of Contents (ToC).
    - [ ] Include a Colab button after that link.

### GitHub

- [ ] **Commits signed**: All commits must be GPG or SSH signed.
- [ ] **DCO Compliance**: Developer Certificate of Origin (DCO) applies to the code, documentation, and any example data provided. Ensure commits are signed off.

2024-11-07 14:48 UTC, bjhargrave requested changes

2024-11-07 14:48 UTC, bjhargrave commented on recipes/AI-Agents/Travel planner agent.ipynb
> +{"cells":[{"cell_type":"markdown","metadata":{},"source":["# Build a Travel planner agentic system using the Granite-3.0-8B-Instruct model in watsonx.ai\n","\n","\n","**Author**: Manoj Jahgirdar\n","
The notebook is a single line file. You probably want to run the pre-commit hook to format it better.

2024-11-07 14:48 UTC, bjhargrave commented on recipes/AI-Agents/Travel planner agent.ipynb
> +{"cells":[{"cell_type":"markdown","metadata":{},"source":["# Build a Travel planner agentic system using the Granite-3.0-8B-Instruct model in watsonx.ai\n","\n","\n","**Author**: Manoj Jahgirdar\n","
You will also want to add this recipe to the .github/notebool_lists/vanilla_notebooks.txt file so that the CI build will test the notebook.

2024-11-07 15:10 UTC, manojjahgirdar commented on recipes/AI-Agents/Travel planner agent.ipynb
> +{"cells":[{"cell_type":"markdown","metadata":{},"source":["# Build a Travel planner agentic system using the Granite-3.0-8B-Instruct model in watsonx.ai\n","\n","\n","**Author**: Manoj Jahgirdar\n","
I wen't through the https://github.com/ibm-granite-community/community/blob/main/CONTRIBUTING.md I couldn't find how to run the pre-commit hook. Is there a guide that I can follow to run the hook? Thanks.

2024-11-07 15:10 UTC, manojjahgirdar commented on recipes/AI-Agents/Travel planner agent.ipynb
> +{"cells":[{"cell_type":"markdown","metadata":{},"source":["# Build a Travel planner agentic system using the Granite-3.0-8B-Instruct model in watsonx.ai\n","\n","\n","**Author**: Manoj Jahgirdar\n","
Added! Thanks.

2024-11-07 15:26 UTC, bjhargrave commented on recipes/AI-Agents/Travel planner agent.ipynb
> +{"cells":[{"cell_type":"markdown","metadata":{},"source":["# Build a Travel planner agentic system using the Granite-3.0-8B-Instruct model in watsonx.ai\n","\n","\n","**Author**: Manoj Jahgirdar\n","
You need to [install](https://pre-commit.com/#install) the pre-commit tool. I used `brew install pre-commit` on my Mac.

Then you can run

```sh
pre-commit run --files <path-to-notebook-file>
```

You can also run `pre-commit install` to install a git hook to automatically run in the repo when you git commit.

2024-11-07 16:04 UTC, bjhargrave commented on recipes/AI-Agents/travel_planner_agent.ipynb
> +    "    project_id = os.environ[\"PROJECT_ID\"]\n",
We provide the following env vars for the automated testing:

```
WATSONX_APIKEY
WATSONX_PROJECT_ID
WATSONX_URL
```

So if you could change to use these env var names, then the testing can proceed.

2024-11-07 16:05 UTC, bjhargrave commented on recipes/AI-Agents/travel_planner_agent.ipynb
> +    "    project_id = os.environ[\"PROJECT_ID\"]\n",
See also:

> Standard access to secrets and variables Include !pip install git+https://github.com/ibm-granite-community/utils in the first code cell in order to make get_env_var available to accessing secrets and variables in the recipe.

2024-11-07 16:10 UTC, manojjahgirdar commented on recipes/AI-Agents/travel_planner_agent.ipynb
> +    "    project_id = os.environ[\"PROJECT_ID\"]\n",
Done, updated the same.

2024-11-07 17:33 UTC, bjhargrave commented
The ci build failed with an import error. I think you may be miss installing a needed package.

2024-11-08 12:19 UTC, manojjahgirdar commented
Ok let me fix the import statements

2024-11-08 13:49 UTC, manojjahgirdar commented
Hi @bjhargrave, I have fixed the import statement, how do I trigger the CI builds?

2024-11-08 13:54 UTC, manojjahgirdar commented
It failed again, this time it says `WATSONX_URL` not found. If you see I have defined it correctly in the notebook.

2024-11-08 13:59 UTC, bjhargrave commented
`pull_request` workflows do not have access to the secrets. I started a workflow which does.

2024-11-08 14:31 UTC, manojjahgirdar commented
@bjhargrave can you rerun the CI pipeline now?

2024-11-14 11:41 UTC, manojjahgirdar commented
@bjhargrave can you rerun the CI pipeline now?

2024-11-14 14:19 UTC, bjhargrave commented
In looking at the code in the notebook, it does not seem to use the Granite 3 prompts for tool use: https://www.ibm.com/granite/docs/models/granite/#tool-usefunction-calling-weather-scenario

It just looks like vanilla langchain tool use.

2024-11-14 14:59 UTC, manojjahgirdar commented
I just referred to the <https://github.com/ibm-granite-community/granite-snack-cookbook/blob/main/recipes/AI-Agents/Agentic_RAG.ipynb> recipe and tried to solve this new use case. I will try to change the prompt if that is absolutely required. 

Changing the prompt may not give desired output, I can still give it a try.

2024-11-14 15:11 UTC, bjhargrave commented
Understood. I am just trying to see if we should, in these Granite recipes, exploit the Granite prompt architecture for things like tool calling. @adampingel Do you have an opinion here? I know that many of the extant recipes were written before Granite 3 was released. But I would think that as we add new recipes, we should lean in to the Granite prompt architecture.

BTW, I have hacked on the existing Function_Calling snack to use the Granite prompt tool calling. I can make a PR for that update soon.

2024-11-22 12:48 UTC, manojjahgirdar commented
Hi @bjhargrave, I have updated the prompt to use granite 3.0 prompt for tool calling. Can you rerun the pipeline to test it? Thanks.

2024-11-22 15:08 UTC, bjhargrave commented
You also need to run the pre-commit hooks to clean up the notebook. There is also a readme conflict to resolve.

2024-11-22 17:47 UTC, manojjahgirdar commented
Ran the pre-commit hook and resolved the readme conflict. Can you run the pipeline once again?

2024-11-23 03:10 UTC, manojjahgirdar commented
@bjhargrave The pipeline completed successfully. Are we good to merge the PR? Thanks.

2024-11-26 18:01 UTC, bjhargrave requested changes
Please fix the link. Otherwise the notebook looks good!

2024-11-26 18:01 UTC, bjhargrave commented on README.md
> +   <a target="_blank" href="https://colab.research.google.com/github/ibm-granite-community/granite-snack-cookbook/blob/main/recipes/Load_LoRA_from_Huggingface/Load_LoRA_from_Huggingface.ipynb">
```suggestion
   <a target="_blank" href="https://colab.research.google.com/github/ibm-granite-community/granite-snack-cookbook/blob/main/recipes/AI-Agents/travel_planner_agent.ipynb">
```

The link should refer to the new recipe.

2024-11-27 07:21 UTC, manojjahgirdar commented
Updated the link.

2024-11-27 15:44 UTC, bjhargrave approved these changes

2024-11-27 15:47 UTC, merged