Invoice Extraction
ibm-granite-community/granite-snack-cookbook pull request #84
Opened 2024-11-20 10:22 UTC by SinghSuryaDeep

## PR Checklist

### Model Interaction

- [ ] **Flexible LLM platform support** The platform should be easily switchable. Use LangChain or LlamaIndex.
- [ ] **Use prompt guide corresponding to the model**  For example for [Granite 3.x Language Models](https://www.ibm.com/granite/docs/models/granite/#prompt-anatomy)

### Data

- [ ] **Example data**: Follow the example data guidance.

### Notebook requirements

- [ ] **Notebook outputs cleared**: Ensure all notebook outputs are cleared.
- [ ] **Automated testing**: Add the recipe to the automated tests as described [here](https://github.com/ibm-granite-community/community/wiki/Automated-Validation)
- [ ] **Test in Google Colab**:
    - [ ] Test that it works in Google Colab (Python 3.10.12).
    - [ ] Colab has its own package set and Python version, so ensure compatibility.
- [ ] **Test locally**:
    - [ ] Ensure the code works in a fresh Python virtual environment (venv).
- [ ] **Standard access to secrets and variables** Include `!pip install git+https://github.com/ibm-granite-community/utils` in the first code cell in order to make `get_env_var` available to accessing secrets and variables in the recipe.

### Incoming References

- [ ] **README.md updates**:
    - [ ] Add a link to the recipe in the Table of Contents (ToC).
    - [ ] Include a Colab button after that link.

### GitHub

- [ ] **Commits signed**: All commits must be GPG or SSH signed.
- [ ] **DCO Compliance**: Developer Certificate of Origin (DCO) applies to the code, documentation, and any example data provided. Ensure commits are signed off.

2024-11-26 21:24 UTC, bjhargrave requested changes
Thanks for the update. I have some comments here. Also, please add this notebook's path to .github/notebook_lists/vanilla_notebooks.txt so the notebooks will be tested in the build.

2024-11-26 21:24 UTC, bjhargrave commented on recipes/Invoice-Extraction/Granite_Recipes_Invoices.ipynb
> +   "source": []
There are a number of empty cells in the notebook which should be removed.

2024-11-26 21:24 UTC, bjhargrave commented on recipes/Invoice-Extraction/Granite_Recipes_Invoices.ipynb
> +    "    base_url = \"https://raw.githubusercontent.com/SinghSuryaDeep/Granite_Recipes_Invoices/main/Invoices/\"\n",
This URL is to your fork. It will need to point to the main repo before we merge.

2024-11-26 21:24 UTC, bjhargrave commented on recipes/Invoice-Extraction/Granite_Recipes_Invoices.ipynb
> +    "Set up the necessary credentials and folder path to process invoices using the InvoiceProcessor class."
We may want more explanatory text here as this cell is the culmination of the notebook. Also there are a number of empty code cells here.

2024-11-27 17:23 UTC, SinghSuryaDeep commented on recipes/Invoice-Extraction/Granite_Recipes_Invoices.ipynb
> +   "source": []
I have made the changes mentioned above.

2024-11-27 17:24 UTC, SinghSuryaDeep commented on recipes/Invoice-Extraction/Granite_Recipes_Invoices.ipynb
> +    "Set up the necessary credentials and folder path to process invoices using the InvoiceProcessor class."
I have made the changes mentioned above.

2024-11-27 17:24 UTC, bjhargrave commented on recipes/Invoice-Extraction/Granite_Recipes_Invoices.ipynb
> +   "source": []
Please rebase your work on the tip of the main branch.

2024-11-27 17:27 UTC, SinghSuryaDeep commented on recipes/Invoice-Extraction/Granite_Recipes_Invoices.ipynb
> +    "    base_url = \"https://raw.githubusercontent.com/SinghSuryaDeep/Granite_Recipes_Invoices/main/Invoices/\"\n",
The folder path is necessary to test the notebook; otherwise, the notebook won't execute, and there will be no results. We can use it for testing, but when making the final commit, we can change the path.

2024-11-28 03:51 UTC, SinghSuryaDeep commented on recipes/Invoice-Extraction/Granite_Recipes_Invoices.ipynb
> +   "source": []
Please check now.

2024-12-02 13:12 UTC, bjhargrave commented on recipes/Invoice-Extraction/Granite_Recipes_Invoices.ipynb
> +    "    base_url = \"https://raw.githubusercontent.com/SinghSuryaDeep/Granite_Recipes_Invoices/main/Invoices/\"\n",
This URL points to different invoices than are included in this PR. Please use `https://raw.githubusercontent.com/SinghSuryaDeep/granite-snack-cookbook/refs/heads/main/recipes/Invoice-Extraction/Invoices/` for testing since that is the URL for the invoices in this PR.

2024-12-02 13:13 UTC, bjhargrave commented
Also, please add this notebook's path to .github/notebook_lists/vanilla_notebooks.txt so the notebooks will be tested in the build.

2024-12-02 14:15 UTC, SinghSuryaDeep commented
I have changed the invoice path as mentioned above and added the notebook path to the vanilla_notebooks.txt file.

2024-12-02 14:33 UTC, bjhargrave approved these changes

2024-12-02 14:34 UTC, bjhargrave commented
@adampingel I think this is ready to merge.

2024-12-03 03:37 UTC, adampingel commented
@SinghSuryaDeep 

1. Where are the invoice pdfs from?  We need to be able to distribute all data under CDLA Permissive 2.0
2. Please create an entry in the top-level README.md for these -- I think under the first section of recipes

2024-12-03 04:01 UTC, SinghSuryaDeep commented
@adampingel 

1. The invoice PDF contains mocked-up data. The numbers and names are not real.
2. I have added an entry in the README.md file for invoice extraction.

2025-01-06 19:39 UTC, SinghSuryaDeep commented
Hi @bjhargrave and @adampingel 
I tested the invoice extraction notebook and updated the GitHub repository as well. Could you please try rerunning the pipeline again. Thanks

2025-01-09 09:07 UTC, SinghSuryaDeep commented
@adampingel and @bjhargrave 

Just a gentle reminder regarding the PR. Please let me know if any action or additional information is required from my side. If not, may we proceed with merging?

Thanks in advance!

2025-01-09 14:18 UTC, merged

2025-01-09 14:19 UTC, bjhargrave commented
Thanks @SinghSuryaDeep!