RAG with Docling using hosted Granite through Replicate
ibm-granite-community/granite-snack-cookbook pull request #97
Opened 2024-12-19 10:02 UTC by mingxzhao

## PR Checklist

Fixes #76 

### Model Interaction

- [ ] **Flexible LLM platform support** The platform should be easily switchable. Use LangChain or LlamaIndex.
- [ ] **Use prompt guide corresponding to the model**  For example for [Granite 3.x Language Models](https://www.ibm.com/granite/docs/models/granite/#prompt-anatomy)

### Data

- [ ] **Example data**: Follow the example data guidance.

### Notebook requirements

- [ ] **Notebook outputs cleared**: Ensure all notebook outputs are cleared.
- [ ] **Automated testing**: Add the recipe to the automated tests as described [here](https://github.com/ibm-granite-community/community/wiki/Automated-Validation)
- [ ] **Test in Google Colab**:
    - [ ] Test that it works in Google Colab (Python 3.10.12).
    - [ ] Colab has its own package set and Python version, so ensure compatibility.
- [ ] **Test locally**:
    - [ ] Ensure the code works in a fresh Python virtual environment (venv).
- [ ] **Standard access to secrets and variables** Include `!pip install git+https://github.com/ibm-granite-community/utils` in the first code cell in order to make `get_env_var` available to accessing secrets and variables in the recipe.

### Incoming References

- [ ] **README.md updates**:
    - [ ] Add a link to the recipe in the Table of Contents (ToC).
    - [ ] Include a Colab button after that link.

### GitHub

- [ ] **Commits signed**: All commits must be GPG or SSH signed.
- [ ] **DCO Compliance**: Developer Certificate of Origin (DCO) applies to the code, documentation, and any example data provided. Ensure commits are signed off.

2024-12-19 10:04 UTC, mingxzhao commented
@bjhargrave @gabe-l-hart

2024-12-19 12:36 UTC, bjhargrave requested changes
You also want to add this notebook to the .github/notebook_lists/vanilla_notebooks.txt file (which means it is CI tested; although it won't have access to the secrets in a PR) and also to the README.md.

2024-12-19 12:36 UTC, bjhargrave commented on recipes/RAG/Granite_Docling_RAG.ipynb
> +        "Welcome to this hands-on workshop! In this session, you'll learn to harness the power of advanced tools to build AI-powered document retrieval systems. We will guide you through:\n",
This is a recipe (which could be used in a workshop) but it is not a workshop per se.

2024-12-19 12:36 UTC, bjhargrave commented on recipes/RAG/Granite_Docling_RAG.ipynb
> +        "3. **[LangChain](https://github.com/hwchase17/langchain):** A powerful framework for building applications powered by language models, designed to simplify complex workflows and integrate ex
Is this the proper langchain GitHub repo?

2024-12-19 12:36 UTC, bjhargrave commented on recipes/RAG/Granite_Docling_RAG.ipynb
> +        "pycharm": {
You will want to run this through the pre-commit hook to clean up some notebook fields.

2024-12-19 12:36 UTC, bjhargrave commented on recipes/RAG/Granite_Docling_RAG.ipynb
> +        "    \"langchain_community<0.3.0\" \\\n",
I am trying to remove these version specifiers. See if the recipe works without them.

2024-12-20 01:31 UTC, mingxzhao commented
@adampingel

2024-12-20 14:18 UTC, bjhargrave commented on README.md
> +   </a>
You lost a blank line before the markdown heading.

2025-01-02 20:33 UTC, merged